# GRPO Algorithm Configuration
defaults: "grpo-deepscaler-1.5b-8K.yaml"

grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 2

loss_fn:
  reference_policy_kl_penalty: 0.001
  ratio_clip_max: 0.28


policy:
  max_total_sequence_length: 16384

  train_global_batch_size: 32
  fsdp_offload_enabled: false